[build]
  command = "npx prisma generate && prisma db push && prisma migrate deploy && prisma db seed && prisma db seed-services && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
